
- name: Copying KEY private root
  copy:
    src: ../files/{{ path_ipsec }}/private/ca-key.pem
    dest: /etc/ipsec.d/private/ca-key.pem
    owner: root
    group: root        
    mode: 0644


- name: Copying CERT root center
  copy:
    src: ../files/{{ path_ipsec }}/cacerts/ca-cert.pem
    dest: /etc/ipsec.d/cacerts/ca-cert.pem
    owner: root
    group: root
    mode: 0644

- name: Copying KEY private vpn 
  copy:
    src: ../files/{{ path_ipsec }}/private/server-key.pem
    dest: /etc/ipsec.d/private/server-key.pem
    owner: root
    group: root        
    mode: 0644

- name: Copying CERT vpn
  copy:
    src: ../files/{{ path_ipsec }}/certs/server-cert.pem
    dest: /etc/ipsec.d/certs/server-cert.pem
    owner: root
    group: root        
    mode: 0644


- name: RE-Generate CERT vpn
  ansible.builtin.shell: pki --pub --in /etc/ipsec.d/private/server-key.pem --type rsa | pki --issue --lifetime 1825 --cacert /etc/ipsec.d/cacerts/{{ ca_cert }} --cakey /etc/ipsec.d/private/ca-key.pem --dn "CN={{ domain }}" --san {{ domain }} --flag serverAuth --flag ikeIntermediate --outform pem > /etc/ipsec.d/certs/server-cert.pem
#  register: ser_cert
#  notify: restart strongswan
